# Generated by Django 6.1.1 on 2026-09-10 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mapping", "0001_initial"),
        ("Patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapping",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Patient.patient"
            ),
        ),
    ]
