# Generated by Django 6.1.1 on 2026-09-11 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Doctors", "0001_initial"),
        ("Mapping", "0002_alter_mapping_patient"),
        ("Patient", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mapping",
            constraint=models.UniqueConstraint(
                fields=("doctor", "patient"), name="unique_doctor_patient"
            ),
        ),
    ]
